# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2
updates:
 - package-ecosystem: "devcontainers"
   directory: "/"
   schedule:
     interval: weekly
=======
version: 2
updates:
  - package-ecosystem: "npm" # Especifica el ecosistema de paquetes (por ejemplo, npm, pip, maven, etc.)
    directory: "/" # La ubicación del archivo package.json en el directorio raíz
    schedule:
      interval: "weekly" # Dependabot verificará actualizaciones semanalmente
  - package-ecosystem: "pip" # Para un proyecto Python
    directory: "/path/to/your/python/project" # Ruta al directorio donde está el archivo requirements.txt
    schedule:
      interval: "weekly" # Dependabot verificará actualizaciones semanalmente
