name: Create Azure Resources

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Log in to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Install Azure CLI and Bicep
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        az bicep install

    - name: Print parameters for debugging
      run: |
        echo "Resource Group: ${{ secrets.AZURE_RESOURCE_GROUP }}"
        echo "Subscription ID: ${{ secrets.AZURE_SUBSCRIPTION }}"
        echo "Name Prefix: ${{ secrets.NAME_PREFIX }}"

    - name: Deploy Bicep template
      run: |
        az deployment group create \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --template-file config/main.bicep \
          --parameters namePrefix=${{ secrets.NAME_PREFIX }} \
          --subscription ${{ secrets.AZURE_SUBSCRIPTION }}
