name: Deploy Azure Resources

on:
  workflow_dispatch:  # Permite ejecutar el workflow manualmente desde la interfaz de GitHub

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Azure CLI
        uses: azure/setup-azure-cli@v1
        with:
          azure-version: 'latest'

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep template
        run: |
          az deployment group create --resource-group ${{ secrets.AZURE_RG }} --template-file ./path-to-your-template.bicep --parameters namePrefix=${{ secrets.AZURE_PREFIX }}
